name: First Workflow 
on: workflow_dispatch 
jobs: 
  first-job: # name of the job 
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting 
        run: echo "Hello world"
      - name: done by
        run: echo "Sone - bye"
